name: Deploy to Vercel

on:
    workflow_run:
        workflows: ["Build project and publish"]
        branches: [main]
        types: [completed]
    workflow_dispatch:

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy production build
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'success') }}
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: build

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install Vercel CLI
              run: npm install -g vercel@latest

            - name: Deploy to Vercel
              run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

        timeout-minutes: 15
